from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class SimulationSpec:
    simulation_id: str
    category: str
    script_relative_path: str
    metrics_filename: str
    artifact_filenames: tuple[str, ...]
    smoke_env: dict[str, str]
    hard_env: dict[str, str] | None = None
    required_summary_keys: tuple[str, ...] = ()
    minimum_summary_values: tuple[tuple[str, float], ...] = ()
    maximum_summary_values: tuple[tuple[str, float], ...] = ()
    required_modules: tuple[str, ...] = ()

    def script_path(self, project_root: Path) -> Path:
        return project_root / self.script_relative_path


SIMULATION_SPECS: dict[str, SimulationSpec] = {
    "capacity_scaling": SimulationSpec(
        simulation_id="capacity_scaling",
        category="compression",
        script_relative_path="neuroloc/simulations/memory/capacity_scaling.py",
        metrics_filename="capacity_scaling_metrics.json",
        artifact_filenames=("capacity_scaling.png", "capacity_scaling_metrics.json"),
        smoke_env={
            "CAPACITY_NETWORK_SIZES": "64,128",
            "CAPACITY_LOAD_FACTORS": "0.05,0.10,0.138",
            "CAPACITY_TRIALS": "2",
            "CAPACITY_MAX_ITERS": "12",
        },
        required_summary_keys=("binary_at_target_alpha", "ternary_at_target_alpha"),
    ),
    "rate_coded_spike": SimulationSpec(
        simulation_id="rate_coded_spike",
        category="compression",
        script_relative_path="neuroloc/simulations/prototypes/rate_coded_spike.py",
        metrics_filename="rate_coded_spike_metrics.json",
        artifact_filenames=("rate_coded_spike.png", "rate_coded_spike_metrics.json"),
        smoke_env={
            "RATE_SPIKE_N_NEURONS": "128",
            "RATE_SPIKE_N_PATTERNS": "5,10",
            "RATE_SPIKE_TRIALS": "2",
            "RATE_SPIKE_MAX_ITERS": "12",
        },
        required_summary_keys=("reference_cosine.binary", "reference_cosine.ternary", "reference_cosine.rate"),
    ),
    "hierarchical_ternary": SimulationSpec(
        simulation_id="hierarchical_ternary",
        category="compression",
        script_relative_path="neuroloc/simulations/sparse_coding/hierarchical_ternary.py",
        metrics_filename="hierarchical_ternary_metrics.json",
        artifact_filenames=("hierarchical_ternary.png", "hierarchical_ternary_metrics.json"),
        smoke_env={
            "HTERN_D_VALUES": "64,256",
            "HTERN_K_FRACTIONS": "0.05,0.20,0.41",
            "HTERN_N_SAMPLES": "64",
            "HTERN_TRIALS": "2",
        },
        required_summary_keys=(
            "standard_reference_mi",
            "standard_reference_cka",
            "selected_hierarchical_reference_mi",
            "selected_hierarchical_reference_cka",
        ),
    ),
    "asymmetric_outer_product_recall": SimulationSpec(
        simulation_id="asymmetric_outer_product_recall",
        category="compression",
        script_relative_path="neuroloc/simulations/memory/asymmetric_outer_product_recall.py",
        metrics_filename="asymmetric_outer_product_recall_metrics.json",
        artifact_filenames=("asymmetric_outer_product_recall.png", "asymmetric_outer_product_recall_metrics.json"),
        smoke_env={
            "ASYM_TRIALS": "2",
            "ASYM_PATTERN_COUNTS": "8,16",
            "ASYM_QUERY_NOISE": "0.0,0.1",
            "ASYM_DECAYS": "0.4,0.8",
        },
        required_summary_keys=("best_exact_query_encoding", "selected_exact_query_raw_cosine"),
    ),
    "correction_field_capacity": SimulationSpec(
        simulation_id="correction_field_capacity",
        category="compression",
        script_relative_path="neuroloc/simulations/memory/correction_field_capacity.py",
        metrics_filename="correction_field_capacity_metrics.json",
        artifact_filenames=(
            "correction_field_capacity_heatmaps.png",
            "correction_field_capacity_summary.png",
            "correction_field_capacity_metrics.json",
        ),
        smoke_env={
            "CF_HEAD_DIMS": "32,64",
            "CF_PATTERN_COUNTS": "4,8,16",
            "CF_PRED_QUALITIES": "0.0,0.9,0.99",
            "CF_DECAYS": "0.5,0.9",
            "CF_TRIALS": "2",
        },
        required_summary_keys=(
            "capacity_raw_vs_corrfield_by_quality",
            "cosine_gain_by_quality_and_patterns",
            "threshold_shift_by_decay",
        ),
    ),
    "correction_field_trained_prediction": SimulationSpec(
        simulation_id="correction_field_trained_prediction",
        category="compression",
        script_relative_path="neuroloc/simulations/memory/correction_field_trained_prediction.py",
        metrics_filename="correction_field_trained_prediction_metrics.json",
        artifact_filenames=(
            "correction_field_trained_prediction_heatmaps.png",
            "correction_field_trained_prediction_summary.png",
            "correction_field_trained_prediction_metrics.json",
        ),
        smoke_env={
            "CFT_HEAD_DIMS": "32",
            "CFT_PATTERN_COUNTS": "4,8",
            "CFT_TEMPORAL_CORRELATIONS": "0.5,0.9",
            "CFT_DECAYS": "0.5,0.9",
            "CFT_TRIALS": "2",
            "CFT_TRAIN_SEQUENCES": "64",
            "CFT_TRAIN_SEQUENCE_LENGTH": "16",
            "CFT_TRAIN_ITERS": "25",
            "CFT_BATCH_SIZE": "32",
        },
        required_summary_keys=(
            "memory_substrate_capacity_delta_by_temporal_correlation",
            "reconstruction_capacity_gain",
            "observed_prediction_quality_by_correlation",
        ),
    ),
    "multi_resolution_head_split": SimulationSpec(
        simulation_id="multi_resolution_head_split",
        category="compression",
        script_relative_path="neuroloc/simulations/memory/multi_resolution_head_split.py",
        metrics_filename="multi_resolution_head_split_metrics.json",
        artifact_filenames=(
            "multi_resolution_head_split.png",
            "multi_resolution_head_split_metrics.json",
        ),
        smoke_env={
            "MRHS_STREAM_LENGTHS": "32,64",
            "MRHS_HEAD_DIMS": "32,64",
            "MRHS_TRIALS": "2",
            "MRHS_QUERIES_PER_CLASS": "4",
        },
        required_summary_keys=(
            "recall_by_class_and_configuration",
            "capacity_gain_split_over_uniform_by_class",
            "crossover_pattern_count_by_class",
        ),
    ),
    "wta_dynamics": SimulationSpec(
        simulation_id="wta_dynamics",
        category="spiking",
        script_relative_path="neuroloc/simulations/lateral_inhibition/wta_dynamics.py",
        metrics_filename="wta_dynamics_metrics.json",
        artifact_filenames=("wta_dynamics.png", "wta_dynamics_anchor.png", "wta_dynamics_metrics.json"),
        smoke_env={
            "WTA_N_NEURONS": "40",
            "WTA_TARGET_FRACTIONS": "0.10,0.41",
            "WTA_NOISE_LEVELS": "0.2,0.6",
            "WTA_SELECTION_TRIALS": "2",
            "WTA_CALIBRATION_TRIALS": "32",
            "WTA_SCALING_NETWORK_SIZES": "40,80",
            "WTA_SCALING_TARGET_FRACTIONS": "0.10,0.41",
            "WTA_SCALING_TRIALS": "2",
            "WTA_ANCHOR_DURATION_MS": "75",
        },
        required_summary_keys=("kwta_exact_support_recovery", "threshold_exact_support_recovery"),
        required_modules=("brian2",),
    ),
    "lif_fi_curve": SimulationSpec(
        simulation_id="lif_fi_curve",
        category="spiking",
        script_relative_path="neuroloc/simulations/single_neuron/lif_fi_curve.py",
        metrics_filename="lif_leak_validation_metrics.json",
        artifact_filenames=("lif_leak_validation.png", "lif_leak_validation_metrics.json"),
        smoke_env={
            "LIF_GAP_VALUES_MS": "4,16",
            "LIF_GAP_TRIALS": "2",
            "LIF_DRIFT_LENGTHS": "64,128",
            "LIF_DRIFT_TRIALS": "2",
        },
        required_summary_keys=(
            "main_comparison.selected_gap_retained_fraction.integrator_control",
            "main_comparison.selected_max_length_final_abs_mv.integrator_control",
            "spike_probe.selected_gap_second_spike.integrator_control",
        ),
        minimum_summary_values=(("spike_probe.selected_gap_second_spike.integrator_control", 0.01),),
        required_modules=("brian2",),
    ),
    "thinking_loop_prototype": SimulationSpec(
        simulation_id="thinking_loop_prototype",
        category="reasoning",
        script_relative_path="neuroloc/simulations/reasoning/thinking_loop_prototype.py",
        metrics_filename="thinking_loop_prototype_metrics.json",
        artifact_filenames=("thinking_loop_prototype.png", "thinking_loop_prototype_metrics.json"),
        smoke_env={
            "THINK_N_TRAIN": "256",
            "THINK_N_VAL": "128",
            "THINK_N_TEST": "128",
            "THINK_N_EPOCHS": "2",
            "THINK_BATCH_SIZE": "64",
            "THINK_D_MODEL": "24",
            "THINK_DEPTH": "2",
            "THINK_DEEP_DEPTH": "4",
            "THINK_N_LIST": "2,4",
            "THINK_N_TRAIN_CAP": "2",
            "THINK_K_LIST": "1,2",
            "THINK_N_SEEDS": "2",
            "THINK_TRAIN_K": "1",
            "THINK_CONV_K_MAX": "4",
        },
        required_summary_keys=(
            "accuracy_by_K_and_N",
            "per_step_gain_by_task_difficulty",
            "generalization_gap_thinking_vs_feedforward",
            "fixed_point_convergence_fraction",
        ),
        required_modules=("torch",),
    ),
    "slot_buffer_capacity": SimulationSpec(
        simulation_id="slot_buffer_capacity",
        category="phase1_nm",
        script_relative_path="neuroloc/simulations/memory/slot_buffer_capacity.py",
        metrics_filename="slot_buffer_capacity_metrics.json",
        artifact_filenames=("slot_buffer_capacity.png", "slot_buffer_capacity_metrics.json"),
        smoke_env={
            "SLOT_CAP_HEAD_DIMS": "32,64",
            "SLOT_CAP_SLOTS": "16,64",
            "SLOT_CAP_TEMPERATURES": "0.1,1.0",
            "SLOT_CAP_QUERY_NOISE": "0.0,0.1",
            "SLOT_CAP_TRIALS": "2",
        },
        required_summary_keys=(
            "pass_criterion_slot_cosine_mean",
            "pass_criterion_slot_exact_mean",
            "capacity_threshold_by_dim",
            "by_cell",
        ),
    ),
    "slot_surprise_writes": SimulationSpec(
        simulation_id="slot_surprise_writes",
        category="phase1_nm",
        script_relative_path="neuroloc/simulations/memory/slot_surprise_writes.py",
        metrics_filename="slot_surprise_writes_metrics.json",
        artifact_filenames=("slot_surprise_writes.png", "slot_surprise_writes_metrics.json"),
        smoke_env={
            "SLOT_SW_HEAD_DIMS": "64",
            "SLOT_SW_SLOTS": "32",
            "SLOT_SW_DISTANCES": "64,128",
            "SLOT_SW_PREDICTABLE": "0.8,0.9",
            "SLOT_SW_TAUS": "0.05,0.1",
            "SLOT_SW_TEMPERATURE": "0.1",
            "SLOT_SW_TRIALS": "2",
        },
        required_summary_keys=(
            "pass_criterion_threshold",
            "cells",
        ),
    ),
    "contextual_recall_world": SimulationSpec(
        simulation_id="contextual_recall_world",
        category="phase1_nm",
        script_relative_path="neuroloc/simulations/memory/contextual_recall_world.py",
        metrics_filename="contextual_recall_world_metrics.json",
        artifact_filenames=("contextual_recall_world.png", "contextual_recall_world_metrics.json"),
        smoke_env={
            "CTX_WORLD_EPISODES": "16",
            "CTX_WORLD_SEQ_LEN": "10",
            "CTX_WORLD_IDENTITIES": "8",
            "CTX_WORLD_ACTIVE": "3",
            "CTX_WORLD_TRACK_LENGTH": "17",
            "CTX_WORLD_OCCLUSION": "0.2",
            "CTX_WORLD_FEATURE_DROPOUT": "0.3",
        },
        required_summary_keys=(
            "recognition_mean_candidate_count",
            "recollection_mean_lag",
            "prediction_mean_step_distance",
            "compression_mean_ratio",
            "imagination_novelty_rate",
            "reasoning_mean_margin",
        ),
        minimum_summary_values=(("compression_mean_ratio", 1.0),),
    ),
    "slot_key_interference_sweep": SimulationSpec(
        simulation_id="slot_key_interference_sweep",
        category="phase1_nm",
        script_relative_path="neuroloc/simulations/memory/slot_key_interference_sweep.py",
        metrics_filename="slot_key_interference_sweep_metrics.json",
        artifact_filenames=(
            "slot_key_interference_sweep.png",
            "slot_key_interference_sweep_metrics.json",
        ),
        smoke_env={
            "SLOT_INT_HEAD_DIMS": "32,64",
            "SLOT_INT_SLOTS": "16,32",
            "SLOT_INT_CORRELATIONS": "0.0,0.8,0.95",
            "SLOT_INT_TEMPERATURES": "0.1",
            "SLOT_INT_QUERY_NOISE": "0.0",
            "SLOT_INT_TRIALS": "2",
        },
        required_summary_keys=(
            "slot_interference_slope_by_dim",
            "matrix_interference_slope_by_dim",
            "slot_minus_matrix_gain_at_high_correlation",
            "by_cell",
        ),
    ),
    "multi_association_recall": SimulationSpec(
        simulation_id="multi_association_recall",
        category="phase1_nm",
        script_relative_path="neuroloc/simulations/memory/multi_association_recall.py",
        metrics_filename="multi_association_recall_metrics.json",
        artifact_filenames=(
            "multi_association_recall.png",
            "multi_association_recall_metrics.json",
        ),
        smoke_env={
            "MAR_HEAD_DIMS": "32,64",
            "MAR_CUE_COUNTS": "8,12",
            "MAR_VALUES_PER_CUE": "2,3",
            "MAR_QUERY_NOISE": "0.0,0.1",
            "MAR_TEMPERATURE": "0.1",
            "MAR_TRIALS": "2",
        },
        required_summary_keys=(
            "slot_bundle_exact_rate",
            "slot_value_hit_rate",
            "matrix_bundle_exact_rate",
            "matrix_value_hit_rate",
            "slot_minus_matrix_exact_gain",
            "by_cell",
        ),
    ),
    "delayed_cue_world": SimulationSpec(
        simulation_id="delayed_cue_world",
        category="phase1_nm",
        script_relative_path="neuroloc/simulations/memory/delayed_cue_world.py",
        metrics_filename="delayed_cue_world_metrics.json",
        artifact_filenames=(
            "delayed_cue_world.png",
            "delayed_cue_world_metrics.json",
        ),
        smoke_env={
            "DCW_GOALS": "4",
            "DCW_CUE_COUNTS": "1,3",
            "DCW_NOISE_LEVELS": "0.0,0.2,0.4",
            "DCW_DELAY_STEPS": "6",
            "DCW_EPISODES": "48",
        },
        required_summary_keys=(
            "bayes_accuracy_by_noise",
            "last_cue_accuracy_by_noise",
            "memory_advantage_by_noise",
            "oracle_accuracy",
            "no_memory_accuracy",
            "by_cell",
        ),
    ),
    "episodic_separation_completion": SimulationSpec(
        simulation_id="episodic_separation_completion",
        category="biology_phase1",
        script_relative_path="neuroloc/simulations/memory/episodic_separation_completion.py",
        metrics_filename="episodic_separation_completion_metrics.json",
        artifact_filenames=(
            "episodic_separation_completion.png",
            "episodic_separation_completion_metrics.json",
        ),
        smoke_env={
            "ESC_TRIALS": "8",
            "ESC_FEATURE_DIM": "16",
            "ESC_ACTION_COUNT": "4",
            "ESC_OVERLAPS": "0.5,0.9",
            "ESC_CUE_DROPS": "0.0,0.5",
            "ESC_DISTRACTORS": "0,4",
        },
        required_summary_keys=(
            "state_probe_accuracy",
            "action_success",
            "joint_success",
            "separation_margin",
            "completion_accuracy_by_cue_drop",
            "novelty_detection_accuracy",
            "delayed_recall_after_distractors",
            "policy_metrics",
        ),
    ),
    "episodic_replay_reuse": SimulationSpec(
        simulation_id="episodic_replay_reuse",
        category="biology_phase1",
        script_relative_path="neuroloc/simulations/memory/episodic_replay_reuse.py",
        metrics_filename="episodic_replay_reuse_metrics.json",
        artifact_filenames=(
            "episodic_replay_reuse.png",
            "episodic_replay_reuse_metrics.json",
        ),
        smoke_env={
            "ERR_TRIALS": "8",
            "ERR_FEATURE_DIM": "16",
            "ERR_ACTION_COUNT": "4",
            "ERR_CUE_DROPS": "0.25,0.5",
            "ERR_DISTRACTORS": "0,4,8",
            "ERR_REPLAY_STEPS": "3",
            "ERR_DECAY": "0.9",
            "ERR_DISTRACTOR_OVERLAP": "0.75",
        },
        required_summary_keys=(
            "state_probe_accuracy",
            "action_success",
            "joint_success",
            "replay_reuse_gain",
            "targeted_vs_random_replay_gap",
            "distractor_decay_curve",
            "state_probe_accuracy_by_cue_drop",
            "policy_metrics",
        ),
    ),
    "contextual_gate_routing": SimulationSpec(
        simulation_id="contextual_gate_routing",
        category="biology_phase1",
        script_relative_path="neuroloc/simulations/memory/contextual_gate_routing.py",
        metrics_filename="contextual_gate_routing_metrics.json",
        artifact_filenames=(
            "contextual_gate_routing.png",
            "contextual_gate_routing_metrics.json",
        ),
        smoke_env={
            "CGR_TRIALS": "24",
            "CGR_CUES": "6",
            "CGR_CONTEXTS": "3",
            "CGR_ACTIONS": "4",
            "CGR_CONTEXTUAL_FRACTION": "0.5",
        },
        required_summary_keys=(
            "state_probe_accuracy",
            "action_success",
            "joint_success",
            "context_gate_dependency",
            "false_bind_rate_under_wrong_context",
            "action_success_by_trial_type",
            "joint_success_by_trial_type",
            "policy_metrics",
        ),
    ),
    "nm_hard_symbolic_test_material": SimulationSpec(
        simulation_id="nm_hard_symbolic_test_material",
        category="hard_symbolic_nm",
        script_relative_path="neuroloc/simulations/memory/nm_hard_symbolic_test_material.py",
        metrics_filename="nm_hard_symbolic_test_material_metrics.json",
        artifact_filenames=("nm_hard_symbolic_test_material_metrics.json",),
        smoke_env={
            "NM_HARD_SYMBOLIC_PROFILE": "smoke",
            "NM_HARD_SYMBOLIC_EPISODES": "4",
            "NM_HARD_SYMBOLIC_SEED": "42",
        },
        hard_env={
            "NM_HARD_SYMBOLIC_PROFILE": "hard",
            "NM_HARD_SYMBOLIC_EPISODES": "32",
            "NM_HARD_SYMBOLIC_SEED": "42",
        },
        required_summary_keys=(
            "family_count",
            "policy_count",
            "state_probe_accuracy",
            "action_success",
            "joint_success",
            "exact_recall",
            "degraded_cue_recall",
            "oracle_joint_success",
            "no_memory_joint_success",
            "recency_only_joint_success",
            "shuffled_address_joint_success",
            "targeted_replay_gain",
            "interference_slope",
            "reuse_advantage",
            "hard_case_rollout_gain",
            "hard_case_pre_rollout_gap",
            "hard_minus_easy_rollout_gain",
            "compression_bit_saving_fraction",
            "bits_written_per_successful_episode",
            "verbatim_within_budget",
            "compressed_within_budget",
            "gate_open_fraction",
            "memory_output_vs_residual_norm",
            "slot_address_entropy",
            "address_margin",
            "write_frequency",
            "read_concentration",
            "retention_over_delay",
            "compression_budget",
            "reconstruction_error",
            "leakage_violation_count",
            "contract_field_violation_count",
        ),
        minimum_summary_values=(
            ("oracle_joint_success", 0.98),
            ("targeted_replay_gain", 0.1),
            ("interference_slope", 0.1),
            ("reuse_advantage", 0.1),
            ("hard_case_rollout_gain", 0.1),
            ("hard_case_pre_rollout_gap", 0.1),
            ("hard_minus_easy_rollout_gain", 0.1),
            ("compression_bit_saving_fraction", 0.1),
            ("compressed_within_budget", 0.98),
            ("gate_open_fraction", 0.1),
            ("memory_output_vs_residual_norm", 0.1),
            ("slot_address_entropy", 0.1),
            ("address_margin", 0.1),
            ("write_frequency", 0.1),
            ("read_concentration", 0.1),
            ("retention_over_delay", 0.98),
        ),
    ),
    "eligibility_gated_local_commit": SimulationSpec(
        simulation_id="eligibility_gated_local_commit",
        category="eligibility_commit",
        script_relative_path="neuroloc/simulations/memory/eligibility_gated_local_commit.py",
        metrics_filename="eligibility_gated_local_commit_metrics.json",
        artifact_filenames=("eligibility_gated_local_commit_metrics.json",),
        smoke_env={
            "ELIG_COMMIT_PROFILE": "smoke",
            "ELIG_COMMIT_EPISODES": "4",
            "ELIG_COMMIT_SEED": "42",
        },
        hard_env={
            "ELIG_COMMIT_PROFILE": "hard",
            "ELIG_COMMIT_EPISODES": "32",
            "ELIG_COMMIT_SEED": "42",
        },
        required_summary_keys=(
            "family_count",
            "policy_count",
            "episode_count",
            "state_probe_accuracy",
            "action_success",
            "joint_success",
            "delayed_use_success",
            "exact_recall",
            "oracle_joint_success",
            "oracle_commit_oracle_exposure_joint_success",
            "no_memory_joint_success",
            "recency_only_joint_success",
            "shuffled_address_joint_success",
            "random_trace_commit_f1",
            "no_trace_joint_success",
            "oracle_mark_no_commit_joint_success",
            "no_commit_oracle_exposure_joint_success",
            "hand_opened_exposure_joint_success",
            "always_commit_unlimited_joint_success",
            "always_commit_unlimited_within_budget",
            "always_commit_matched_budget_joint_success",
            "matched_residual_capacity_joint_success",
            "matched_compute_budget_joint_success",
            "fixed_closed_exposure_action_success",
            "fixed_open_exposure_joint_success",
            "no_memory_control_gap",
            "recency_control_gap",
            "shuffled_address_control_gap",
            "random_trace_control_margin",
            "fixed_closed_exposure_control_gap",
            "fixed_open_exposure_control_gap",
            "matched_residual_capacity_control_gap",
            "matched_compute_budget_control_gap",
            "no_memory_ceiling_pass",
            "recency_only_ceiling_pass",
            "shuffled_address_ceiling_pass",
            "random_trace_ceiling_pass",
            "always_commit_unlimited_budget_fail_pass",
            "always_commit_matched_budget_ceiling_pass",
            "oracle_mark_no_commit_ceiling_pass",
            "no_commit_oracle_exposure_ceiling_pass",
            "hand_opened_exposure_ceiling_pass",
            "fixed_closed_exposure_ceiling_pass",
            "fixed_open_exposure_ceiling_pass",
            "matched_residual_capacity_ceiling_pass",
            "matched_compute_budget_ceiling_pass",
            "mark_success",
            "commit_success",
            "read_success",
            "exposure_success",
            "trace_precision",
            "trace_recall",
            "write_precision",
            "write_recall",
            "commit_f1",
            "commit_latency",
            "false_commit_rate",
            "negative_commit_rejection_rate",
            "output_capacity_precision",
            "output_capacity_recall",
            "oracle_trace_learned_commit_gap",
            "learned_trace_oracle_commit_gap",
            "oracle_commit_learned_exposure_gap",
            "learned_commit_oracle_exposure_gap",
            "bits_committed_per_successful_episode",
            "writes_per_successful_episode",
            "verbatim_trace_bits",
            "always_write_bits",
            "eligibility_commit_bits",
            "task_relevant_bits",
            "useful_bits_fraction",
            "commit_compression_saving_vs_always",
            "memory_output_vs_residual_norm",
            "exposure_noise_cost",
            "bounded_exposure_noise_penalty",
            "leakage_violation_count",
            "contract_field_violation_count",
            "delayed_relevance_oracle_joint",
            "bounded_output_oracle_joint",
            "crossed_split_oracle_joint",
            "compression_frontier_oracle_joint",
        ),
        minimum_summary_values=(
            ("state_probe_accuracy", 0.98),
            ("action_success", 0.98),
            ("joint_success", 0.98),
            ("delayed_use_success", 0.98),
            ("exact_recall", 0.98),
            ("oracle_joint_success", 0.98),
            ("oracle_commit_oracle_exposure_joint_success", 0.98),
            ("always_commit_unlimited_joint_success", 0.98),
            ("mark_success", 0.98),
            ("commit_success", 0.98),
            ("read_success", 0.98),
            ("exposure_success", 0.98),
            ("trace_precision", 0.98),
            ("trace_recall", 0.98),
            ("write_precision", 0.98),
            ("write_recall", 0.98),
            ("commit_f1", 0.98),
            ("negative_commit_rejection_rate", 0.98),
            ("output_capacity_precision", 0.98),
            ("output_capacity_recall", 0.98),
            ("oracle_trace_learned_commit_gap", 0.98),
            ("learned_trace_oracle_commit_gap", 0.98),
            ("oracle_commit_learned_exposure_gap", 0.98),
            ("learned_commit_oracle_exposure_gap", 0.98),
            ("no_memory_control_gap", 0.98),
            ("recency_control_gap", 0.98),
            ("shuffled_address_control_gap", 0.98),
            ("random_trace_control_margin", 0.04),
            ("fixed_closed_exposure_control_gap", 0.98),
            ("fixed_open_exposure_control_gap", 0.98),
            ("matched_residual_capacity_control_gap", 0.98),
            ("matched_compute_budget_control_gap", 0.98),
            ("no_memory_ceiling_pass", 1.0),
            ("recency_only_ceiling_pass", 1.0),
            ("shuffled_address_ceiling_pass", 1.0),
            ("random_trace_ceiling_pass", 1.0),
            ("always_commit_unlimited_budget_fail_pass", 1.0),
            ("always_commit_matched_budget_ceiling_pass", 1.0),
            ("oracle_mark_no_commit_ceiling_pass", 1.0),
            ("no_commit_oracle_exposure_ceiling_pass", 1.0),
            ("hand_opened_exposure_ceiling_pass", 1.0),
            ("fixed_closed_exposure_ceiling_pass", 1.0),
            ("fixed_open_exposure_ceiling_pass", 1.0),
            ("matched_residual_capacity_ceiling_pass", 1.0),
            ("matched_compute_budget_ceiling_pass", 1.0),
            ("delayed_relevance_oracle_joint", 0.98),
            ("bounded_output_oracle_joint", 0.98),
            ("crossed_split_oracle_joint", 0.98),
            ("compression_frontier_oracle_joint", 0.98),
            ("commit_compression_saving_vs_always", 0.1),
            ("memory_output_vs_residual_norm", 0.1),
            ("bounded_exposure_noise_penalty", 0.1),
        ),
    ),
    "oracle_compression_analysis": SimulationSpec(
        simulation_id="oracle_compression_analysis",
        category="oracle_compression",
        script_relative_path="neuroloc/simulations/memory/oracle_compression_analysis.py",
        metrics_filename="oracle_compression_analysis_metrics.json",
        artifact_filenames=("oracle_compression_analysis_metrics.json",),
        smoke_env={
            "ORACLE_COMPRESSION_PROFILE": "smoke",
            "ORACLE_COMPRESSION_HARD_EPISODES": "4",
            "ORACLE_COMPRESSION_ELIGIBILITY_EPISODES": "4",
            "ORACLE_COMPRESSION_SEED": "42",
        },
        hard_env={
            "ORACLE_COMPRESSION_PROFILE": "hard",
            "ORACLE_COMPRESSION_HARD_EPISODES": "32",
            "ORACLE_COMPRESSION_ELIGIBILITY_EPISODES": "32",
            "ORACLE_COMPRESSION_SEED": "42",
        },
        required_summary_keys=(
            "record_count",
            "episode_count",
            "contract_count",
            "surface_count",
            "family_count",
            "mean_verbatim_trace_bits",
            "min_verbatim_trace_bits",
            "max_verbatim_trace_bits",
            "mean_latent_state_bits",
            "min_latent_state_bits",
            "max_latent_state_bits",
            "mean_schema_residual_bits",
            "min_schema_residual_bits",
            "max_schema_residual_bits",
            "mean_imagined_branch_program_bits",
            "min_imagined_branch_program_bits",
            "max_imagined_branch_program_bits",
            "operation_preservation_rate",
            "joint_preservation_rate",
            "action_preservation_rate",
            "address_preservation_rate",
            "bounded_exposure_preservation_rate",
            "replay_rewrite_preservation_rate",
            "branch_reconstruction_preservation_rate",
            "controls_preservation_rate",
            "leakage_free_rate",
            "accepted_rate",
            "strong_oracle_target_count",
            "strong_oracle_target_fraction",
            "strong_oracle_family_count",
            "weak_oracle_family_count",
            "extreme_oracle_target_count",
            "kill_condition_count",
            "leakage_violation_count",
            "weak_oracle_ratio_count",
            "mean_oracle_ratio_latent",
            "min_oracle_ratio_latent",
            "max_oracle_ratio_latent",
            "mean_oracle_ratio_schema_residual",
            "min_oracle_ratio_schema_residual",
            "max_oracle_ratio_schema_residual",
            "mean_oracle_ratio_branch_program",
            "min_oracle_ratio_branch_program",
            "max_oracle_ratio_branch_program",
            "max_oracle_ratio",
            "min_oracle_ratio",
            "hard_symbolic_mean_best_ratio",
            "hard_symbolic_schema_ratio_mean",
            "eligibility_commit_mean_best_ratio",
            "eligibility_commit_ratio_vs_always_write",
            "imagination_recombination_mean_best_ratio",
            "imagination_branch_ratio_mean",
            "no_memory_control_pass",
            "recency_control_pass",
            "shuffled_address_control_pass",
            "verbatim_control_available",
            "compressed_control_available",
            "overclaim_guard_pass",
            "family_mean_best_ratio",
            "surface_mean_best_ratio",
            "trainable_mirror_recommended",
        ),
        minimum_summary_values=(
            ("record_count", 1.0),
            ("surface_count", 2.0),
            ("family_count", 14.0),
            ("operation_preservation_rate", 0.98),
            ("controls_preservation_rate", 0.98),
            ("leakage_free_rate", 0.98),
            ("no_memory_control_pass", 1.0),
            ("recency_control_pass", 1.0),
            ("shuffled_address_control_pass", 1.0),
            ("overclaim_guard_pass", 1.0),
            ("max_oracle_ratio", 10.0),
            ("imagination_recombination_mean_best_ratio", 10.0),
        ),
    ),
    "compression_under_bit_budget_mirror": SimulationSpec(
        simulation_id="compression_under_bit_budget_mirror",
        category="compression_mirror",
        script_relative_path="neuroloc/simulations/memory/compression_under_bit_budget_mirror.py",
        metrics_filename="compression_under_bit_budget_mirror_metrics.json",
        artifact_filenames=("compression_under_bit_budget_mirror_metrics.json",),
        smoke_env={
            "CUBB_MIRROR_PROFILE": "smoke",
            "CUBB_MIRROR_TRAIN_EPISODES": "16",
            "CUBB_MIRROR_VAL_EPISODES": "4",
            "CUBB_MIRROR_TEST_EPISODES": "4",
            "CUBB_MIRROR_TRAIN_EPOCHS": "80",
            "CUBB_MIRROR_SEED": "42",
        },
        hard_env={
            "CUBB_MIRROR_PROFILE": "hard",
            "CUBB_MIRROR_TRAIN_EPISODES": "1024",
            "CUBB_MIRROR_VAL_EPISODES": "256",
            "CUBB_MIRROR_TEST_EPISODES": "512",
            "CUBB_MIRROR_TRAIN_EPOCHS": "80",
            "CUBB_MIRROR_SEED": "42",
        },
        required_summary_keys=(
            "family_count",
            "policy_count",
            "dataset_record_count",
            "train_record_count",
            "validation_record_count",
            "test_record_count",
            "forbidden_input_violation_count",
            "future_observation_violation_count",
            "oracle_joint_success",
            "compressed_oracle_joint_success",
            "verbatim_joint_success",
            "content_routed_sparse_read_joint_success",
            "content_routed_sparse_read_state_success",
            "content_routed_sparse_read_action_success",
            "content_routed_sparse_read_selected_record_count",
            "content_routed_sparse_read_source_selection_recall",
            "content_routed_sparse_read_next_source_selection_recall",
            "content_routed_sparse_read_false_source_selection_rate",
            "content_routed_sparse_read_total_committed_bits",
            "content_routed_sparse_read_within_budget",
            "content_routed_sparse_read_compression_ratio_vs_verbatim",
            "matched_budget_sparse_read_joint_success",
            "matched_budget_sparse_read_state_success",
            "matched_budget_sparse_read_action_success",
            "matched_budget_sparse_read_selected_record_count",
            "matched_budget_sparse_read_total_committed_bits",
            "matched_budget_sparse_read_within_budget",
            "distributed_evidence_record_count",
            "distributed_evidence_sparse_read_joint_success",
            "distributed_evidence_matched_budget_sparse_read_joint_success",
            "distributed_evidence_sparse_read_selected_record_count",
            "distributed_evidence_matched_budget_sparse_read_selected_record_count",
            "distributed_evidence_sparse_read_total_committed_bits",
            "distributed_evidence_matched_budget_sparse_read_total_committed_bits",
            "distributed_evidence_sparse_read_within_budget",
            "distributed_evidence_matched_budget_sparse_read_within_budget",
            "distributed_evidence_compression_needed_flag",
            "tiny_distributed_local_model_authorized",
            "tiny_distributed_full_model_authorized",
            "tiny_distributed_paid_compute_authorized",
            "tiny_distributed_train_record_count",
            "tiny_distributed_validation_record_count",
            "tiny_distributed_test_record_count",
            "tiny_distributed_train_epochs",
            "tiny_distributed_parameter_count",
            "tiny_distributed_train_loss_start",
            "tiny_distributed_train_loss_final",
            "tiny_distributed_decoder_train_loss_start",
            "tiny_distributed_decoder_train_loss_final",
            "tiny_distributed_learned_codec_train_joint_success",
            "tiny_distributed_learned_codec_validation_joint_success",
            "tiny_distributed_learned_codec_test_joint_success",
            "tiny_distributed_learned_codec_test_state_success",
            "tiny_distributed_learned_codec_test_action_success",
            "tiny_distributed_learned_code_oracle_decoder_test_joint_success",
            "tiny_distributed_matched_budget_sparse_read_test_joint_success",
            "tiny_distributed_matched_budget_sparse_read_total_committed_bits",
            "tiny_distributed_learned_codec_total_committed_bits",
            "tiny_distributed_learned_minus_matched_budget_sparse_read",
            "tiny_distributed_engineering_pass",
            "tiny_distributed_oracle_code_learned_decoder_train_joint_success",
            "tiny_distributed_oracle_code_learned_decoder_validation_joint_success",
            "tiny_distributed_oracle_code_learned_decoder_test_joint_success",
            "tiny_distributed_oracle_code_learned_decoder_train_test_joint_gap",
            "factor_heldout_local_model_authorized",
            "factor_heldout_full_model_authorized",
            "factor_heldout_paid_compute_authorized",
            "factor_heldout_train_bucket_count",
            "factor_heldout_validation_bucket_count",
            "factor_heldout_test_bucket_count",
            "factor_heldout_train_validation_bucket_overlap",
            "factor_heldout_train_test_bucket_overlap",
            "factor_heldout_validation_test_bucket_overlap",
            "factor_heldout_test_colors_seen_in_train",
            "factor_heldout_test_shapes_seen_in_train",
            "factor_heldout_train_record_count",
            "factor_heldout_validation_record_count",
            "factor_heldout_test_record_count",
            "factor_heldout_train_epochs",
            "factor_heldout_parameter_count",
            "factor_heldout_train_loss_start",
            "factor_heldout_train_loss_final",
            "factor_heldout_decoder_train_loss_start",
            "factor_heldout_decoder_train_loss_final",
            "factor_heldout_learned_codec_train_joint_success",
            "factor_heldout_learned_codec_validation_joint_success",
            "factor_heldout_learned_codec_test_joint_success",
            "factor_heldout_learned_codec_test_state_success",
            "factor_heldout_learned_codec_test_action_success",
            "factor_heldout_learned_code_oracle_decoder_test_joint_success",
            "factor_heldout_matched_budget_sparse_read_test_joint_success",
            "factor_heldout_matched_budget_sparse_read_total_committed_bits",
            "factor_heldout_learned_codec_total_committed_bits",
            "factor_heldout_learned_minus_matched_budget_sparse_read",
            "factor_heldout_engineering_pass",
            "factor_heldout_oracle_code_learned_decoder_train_joint_success",
            "factor_heldout_oracle_code_learned_decoder_validation_joint_success",
            "factor_heldout_oracle_code_learned_decoder_test_joint_success",
            "factor_heldout_oracle_code_learned_decoder_train_test_joint_gap",
            "no_memory_joint_success",
            "recency_only_joint_success",
            "shuffled_address_joint_success",
            "random_codebook_joint_success",
            "matched_bit_random_code_joint_success",
            "matched_compute_no_code_joint_success",
            "learned_result_count",
            "learned_codec_joint_success",
            "learned_codec_train_joint_success",
            "learned_codec_validation_joint_success",
            "learned_codec_state_probe_accuracy",
            "learned_codec_action_success",
            "learned_codec_encoder_address_accuracy",
            "learned_codec_encoder_payload_accuracy",
            "learned_codec_encoder_payload_color_accuracy",
            "learned_codec_encoder_payload_shape_accuracy",
            "learned_codec_encoder_payload_pos_accuracy",
            "learned_codec_encoder_payload_vel_accuracy",
            "learned_codec_encoder_action_accuracy",
            "learned_codec_encoder_provenance_accuracy",
            "source_event_observed_rate",
            "source_event_complete_rate",
            "source_required_fields_visible_rate",
            "source_state_reconstructable_rate",
            "source_signature_action_ambiguity_rate",
            "learned_codec_unique_code_count",
            "learned_codec_code_collision_rate",
            "learned_codec_train_test_joint_gap",
            "learned_codec_bits_per_success_defined",
            "learned_codec_compression_ratio_vs_verbatim",
            "learned_codec_engineering_pass",
            "learned_codec_paper_track_pass",
            "learned_codec_kill_condition_count",
            "diagnostic_result_count",
            "learned_code_oracle_decoder_joint_success",
            "oracle_code_learned_decoder_joint_success",
            "learned_address_oracle_payload_joint_success",
            "oracle_address_learned_payload_joint_success",
            "provenance_exposed_learned_codec_joint_success",
            "visible_source_codec_joint_success",
            "visible_source_codec_state_success",
            "visible_source_codec_action_success",
            "visible_source_state_oracle_action_oracle_decoder_joint_success",
            "visible_source_state_oracle_action_oracle_decoder_state_success",
            "source_observation_oracle_action_joint_success",
            "source_observation_learned_action_joint_success",
            "provenance_exposed_oracle_decoder_joint_success",
            "provenance_exposed_oracle_decoder_state_success",
            "provenance_exposed_oracle_decoder_action_success",
            "learned_state_oracle_action_joint_success",
            "learned_state_oracle_action_oracle_decoder_joint_success",
            "learned_state_oracle_action_oracle_decoder_state_success",
            "oracle_state_learned_action_joint_success",
            "oracle_state_learned_action_oracle_decoder_joint_success",
            "oracle_state_learned_action_oracle_decoder_action_success",
            "learned_action_only_failure_rate",
            "oracle_decoder_rescue_delta",
            "oracle_encoder_rescue_delta",
            "oracle_address_payload_rescue_delta",
            "provenance_exposure_rescue_delta",
            "provenance_exposed_oracle_decoder_rescue_delta",
            "visible_source_codec_rescue_delta",
            "source_observation_rescue_delta",
            "content_routed_sparse_read_rescue_delta",
            "visible_source_state_rescue_delta",
            "oracle_action_rescue_delta",
            "oracle_state_rescue_delta",
            "oracle_code_learned_decoder_train_joint_success",
            "oracle_code_learned_decoder_validation_joint_success",
            "oracle_code_learned_decoder_test_joint_success",
            "oracle_code_learned_decoder_train_test_joint_gap",
            "oracle_code_learned_decoder_train_state_success",
            "oracle_code_learned_decoder_validation_state_success",
            "oracle_code_learned_decoder_test_state_success",
            "oracle_code_learned_decoder_train_action_success",
            "oracle_code_learned_decoder_validation_action_success",
            "oracle_code_learned_decoder_test_action_success",
            "diagnostic_oracle_input_used",
            "learned_minus_no_memory",
            "learned_minus_recency_only",
            "learned_minus_shuffled_address",
            "learned_minus_random_codebook",
            "learned_minus_content_routed_sparse_read",
            "learned_minus_matched_budget_sparse_read",
            "learned_versus_oracle_codec",
            "state_probe_accuracy",
            "action_success",
            "joint_success",
            "bits_committed_per_successful_episode",
            "compression_ratio_vs_verbatim",
            "rate_distortion_frontier_ready",
            "verbatim_within_budget",
            "compressed_oracle_within_budget",
            "no_memory_gap",
            "recency_gap",
            "shuffled_address_gap",
            "random_codebook_gap",
            "address_margin",
            "address_entropy",
            "read_concentration",
            "write_frequency",
            "memory_output_vs_residual_norm",
            "reconstruction_error",
            "local_mirror_code_authorized",
            "full_model_authorized",
            "paid_compute_authorized",
            "blocked_authorization_violation_count",
        ),
        minimum_summary_values=(
            ("family_count", 1.0),
            ("policy_count", 25.0),
            ("train_record_count", 1.0),
            ("validation_record_count", 1.0),
            ("test_record_count", 1.0),
            ("oracle_joint_success", 0.98),
            ("compressed_oracle_joint_success", 0.98),
            ("verbatim_joint_success", 0.98),
            ("content_routed_sparse_read_joint_success", 0.98),
            ("content_routed_sparse_read_source_selection_recall", 0.98),
            ("content_routed_sparse_read_next_source_selection_recall", 0.98),
            ("matched_budget_sparse_read_within_budget", 0.98),
            ("distributed_evidence_record_count", 1.0),
            ("distributed_evidence_sparse_read_joint_success", 0.98),
            ("distributed_evidence_compression_needed_flag", 1.0),
            ("tiny_distributed_local_model_authorized", 1.0),
            ("tiny_distributed_train_record_count", 1.0),
            ("tiny_distributed_learned_codec_test_joint_success", 0.95),
            ("tiny_distributed_learned_code_oracle_decoder_test_joint_success", 0.95),
            ("tiny_distributed_oracle_code_learned_decoder_test_joint_success", 0.95),
            ("tiny_distributed_learned_minus_matched_budget_sparse_read", 0.95),
            ("tiny_distributed_engineering_pass", 1.0),
            ("factor_heldout_local_model_authorized", 1.0),
            ("factor_heldout_train_record_count", 1.0),
            ("factor_heldout_validation_record_count", 1.0),
            ("factor_heldout_test_record_count", 1.0),
            ("factor_heldout_test_colors_seen_in_train", 1.0),
            ("factor_heldout_test_shapes_seen_in_train", 1.0),
            ("state_probe_accuracy", 0.98),
            ("action_success", 0.98),
            ("joint_success", 0.98),
            ("source_event_observed_rate", 0.98),
            ("source_required_fields_visible_rate", 0.98),
            ("source_state_reconstructable_rate", 0.98),
            ("visible_source_codec_joint_success", 0.98),
            ("visible_source_state_oracle_action_oracle_decoder_joint_success", 0.98),
            ("compression_ratio_vs_verbatim", 1.01),
            ("rate_distortion_frontier_ready", 1.0),
            ("compressed_oracle_within_budget", 0.98),
            ("no_memory_gap", 0.98),
            ("recency_gap", 0.98),
            ("shuffled_address_gap", 0.98),
            ("random_codebook_gap", 0.98),
            ("learned_result_count", 1.0),
            ("diagnostic_result_count", 1.0),
            ("read_concentration", 0.1),
            ("memory_output_vs_residual_norm", 0.1),
            ("local_mirror_code_authorized", 1.0),
        ),
        maximum_summary_values=(
            ("forbidden_input_violation_count", 0.0),
            ("future_observation_violation_count", 0.0),
            ("full_model_authorized", 0.0),
            ("paid_compute_authorized", 0.0),
            ("tiny_distributed_full_model_authorized", 0.0),
            ("tiny_distributed_paid_compute_authorized", 0.0),
            ("factor_heldout_full_model_authorized", 0.0),
            ("factor_heldout_paid_compute_authorized", 0.0),
            ("factor_heldout_train_validation_bucket_overlap", 0.0),
            ("factor_heldout_train_test_bucket_overlap", 0.0),
            ("factor_heldout_validation_test_bucket_overlap", 0.0),
            ("blocked_authorization_violation_count", 0.0),
        ),
        required_modules=("torch",),
    ),
}


SUITES: dict[str, tuple[str, ...]] = {
    "compression": (
        "capacity_scaling",
        "rate_coded_spike",
        "hierarchical_ternary",
        "asymmetric_outer_product_recall",
        "correction_field_capacity",
        "correction_field_trained_prediction",
        "multi_resolution_head_split",
        "oracle_compression_analysis",
    ),
    "spiking": (
        "wta_dynamics",
        "lif_fi_curve",
    ),
    "reasoning": (
        "thinking_loop_prototype",
    ),
    "biology_phase1": (
        "episodic_separation_completion",
        "episodic_replay_reuse",
        "contextual_gate_routing",
    ),
    "phase1_nm": (
        "slot_buffer_capacity",
        "slot_surprise_writes",
        "contextual_recall_world",
        "slot_key_interference_sweep",
        "multi_association_recall",
        "delayed_cue_world",
        "episodic_separation_completion",
        "episodic_replay_reuse",
        "contextual_gate_routing",
    ),
    "hard_symbolic_nm": (
        "nm_hard_symbolic_test_material",
    ),
    "eligibility_commit": (
        "eligibility_gated_local_commit",
    ),
    "oracle_compression": (
        "oracle_compression_analysis",
    ),
    "compression_mirror": (
        "compression_under_bit_budget_mirror",
    ),
    "precompute": (
        "capacity_scaling",
        "rate_coded_spike",
        "hierarchical_ternary",
        "asymmetric_outer_product_recall",
        "correction_field_capacity",
        "correction_field_trained_prediction",
        "multi_resolution_head_split",
        "wta_dynamics",
        "lif_fi_curve",
        "thinking_loop_prototype",
        "slot_buffer_capacity",
        "slot_surprise_writes",
        "contextual_recall_world",
        "slot_key_interference_sweep",
        "multi_association_recall",
        "delayed_cue_world",
        "episodic_separation_completion",
        "episodic_replay_reuse",
        "contextual_gate_routing",
        "nm_hard_symbolic_test_material",
        "eligibility_gated_local_commit",
        "oracle_compression_analysis",
        "compression_under_bit_budget_mirror",
    ),
}


def get_suite_specs(suite_name: str) -> list[SimulationSpec]:
    if suite_name not in SUITES:
        raise KeyError(f"unknown suite: {suite_name}")
    return [SIMULATION_SPECS[item] for item in SUITES[suite_name]]


def all_specs() -> list[SimulationSpec]:
    return list(SIMULATION_SPECS.values())


def to_jsonable(spec: SimulationSpec) -> dict[str, Any]:
    return {
        "simulation_id": spec.simulation_id,
        "category": spec.category,
        "script_relative_path": spec.script_relative_path,
        "metrics_filename": spec.metrics_filename,
        "artifact_filenames": list(spec.artifact_filenames),
        "smoke_env": dict(spec.smoke_env),
        "required_summary_keys": list(spec.required_summary_keys),
        "minimum_summary_values": [
            {"key": dotted_key, "minimum": minimum}
            for dotted_key, minimum in spec.minimum_summary_values
        ],
        "maximum_summary_values": [
            {"key": dotted_key, "maximum": maximum}
            for dotted_key, maximum in spec.maximum_summary_values
        ],
        "required_modules": list(spec.required_modules),
    }
